require('dotenv').config();
const mongoose = require('mongoose');
const Show = require('./models/Show');

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    console.log('Seeding database...');
    
    // Clear existing shows
    await Show.deleteMany({});
    console.log('Cleared existing shows');
    
    const shows = [
      {
        title: 'Avengers: Endgame',
        description: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos\' actions and restore balance to the universe.',
        genre: 'Action',
        language: 'English',
        duration: 181,
        rating: 'PG-13',
        cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson'],
        director: 'Anthony Russo, Joe Russo',
        posterUrl: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
        date: new Date('2025-12-20'),
        time: '18:00',
        venue: 'PVR Cinemas',
        screen: 'Screen 1',
        totalSeats: 150,
        availableSeats: 120,
        price: 350,
        format: 'IMAX',
        status: 'now-showing',
      },
      {
        title: 'Inception',
        description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
        genre: 'Sci-Fi',
        language: 'English',
        duration: 148,
        rating: 'PG-13',
        cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page', 'Tom Hardy', 'Marion Cotillard'],
        director: 'Christopher Nolan',
        posterUrl: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
        date: new Date('2025-12-21'),
        time: '20:00',
        venue: 'INOX Megaplex',
        screen: 'Screen 3',
        totalSeats: 100,
        availableSeats: 85,
        price: 300,
        format: '2D',
        status: 'now-showing',
      },
      {
        title: 'The Dark Knight',
        description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        genre: 'Action',
        language: 'English',
        duration: 152,
        rating: 'PG-13',
        cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Gary Oldman'],
        director: 'Christopher Nolan',
        posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        date: new Date('2025-12-22'),
        time: '15:30',
        venue: 'Cinepolis',
        screen: 'Screen 2',
        totalSeats: 120,
        availableSeats: 95,
        price: 280,
        format: '2D',
        status: 'now-showing',
      },
      {
        title: 'Interstellar',
        description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
        genre: 'Sci-Fi',
        language: 'English',
        duration: 169,
        rating: 'PG-13',
        cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine', 'Matt Damon'],
        director: 'Christopher Nolan',
        posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
        date: new Date('2025-12-23'),
        time: '19:00',
        venue: 'PVR Cinemas',
        screen: 'Screen 4',
        totalSeats: 140,
        availableSeats: 110,
        price: 320,
        format: 'IMAX',
        status: 'now-showing',
      },
      {
        title: 'Joker',
        description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
        genre: 'Thriller',
        language: 'English',
        duration: 122,
        rating: 'R',
        cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy', 'Brett Cullen'],
        director: 'Todd Phillips',
        posterUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
        date: new Date('2025-12-24'),
        time: '21:30',
        venue: 'INOX Megaplex',
        screen: 'Screen 1',
        totalSeats: 90,
        availableSeats: 70,
        price: 290,
        format: '2D',
        status: 'now-showing',
      },
      {
        title: 'Spider-Man: No Way Home',
        description: 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.',
        genre: 'Action',
        language: 'English',
        duration: 148,
        rating: 'PG-13',
        cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch', 'Jacob Batalon', 'Jon Favreau'],
        director: 'Jon Watts',
        posterUrl: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
        date: new Date('2025-12-25'),
        time: '12:00',
        venue: 'Cinepolis',
        screen: 'Screen 5',
        totalSeats: 160,
        availableSeats: 130,
        price: 400,
        format: '3D',
        status: 'now-showing',
      },
      {
        title: 'The Shawshank Redemption',
        description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        genre: 'Drama',
        language: 'English',
        duration: 142,
        rating: 'R',
        cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler', 'Clancy Brown'],
        director: 'Frank Darabont',
        posterUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
        date: new Date('2025-12-26'),
        time: '17:00',
        venue: 'PVR Cinemas',
        screen: 'Screen 2',
        totalSeats: 80,
        availableSeats: 60,
        price: 250,
        format: '2D',
        status: 'now-showing',
      },
      {
        title: 'Parasite',
        description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
        genre: 'Thriller',
        language: 'Korean',
        duration: 132,
        rating: 'R',
        cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik', 'Park So-dam'],
        director: 'Bong Joon-ho',
        posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
        date: new Date('2025-12-27'),
        time: '20:30',
        venue: 'INOX Megaplex',
        screen: 'Screen 2',
        totalSeats: 70,
        availableSeats: 55,
        price: 270,
        format: '2D',
        status: 'now-showing',
      },
      {
        title: 'Dune',
        description: 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.',
        genre: 'Sci-Fi',
        language: 'English',
        duration: 155,
        rating: 'PG-13',
        cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Josh Brolin', 'Zendaya'],
        director: 'Denis Villeneuve',
        posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=8g18jFHCLXk',
        date: new Date('2025-12-28'),
        time: '16:00',
        venue: 'Cinepolis',
        screen: 'Screen 1',
        totalSeats: 130,
        availableSeats: 100,
        price: 380,
        format: 'IMAX',
        status: 'now-showing',
      },
      {
        title: 'The Matrix',
        description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
        genre: 'Sci-Fi',
        language: 'English',
        duration: 136,
        rating: 'R',
        cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving', 'Joe Pantoliano'],
        director: 'Lana Wachowski, Lilly Wachowski',
        posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
        date: new Date('2025-12-29'),
        time: '22:00',
        venue: 'PVR Cinemas',
        screen: 'Screen 3',
        totalSeats: 110,
        availableSeats: 0,
        price: 300,
        format: '2D',
        status: 'now-showing',
      },
      {
        title: 'Oppenheimer',
        description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
        genre: 'Drama',
        language: 'English',
        duration: 180,
        rating: 'R',
        cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh'],
        director: 'Christopher Nolan',
        posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
        date: new Date('2025-12-30'),
        time: '14:30',
        venue: 'INOX Megaplex',
        screen: 'Screen 4',
        totalSeats: 140,
        availableSeats: 115,
        price: 350,
        format: 'IMAX',
        status: 'now-showing',
      },
      {
        title: 'Barbie',
        description: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
        genre: 'Comedy',
        language: 'English',
        duration: 114,
        rating: 'PG-13',
        cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Kate McKinnon', 'Issa Rae'],
        director: 'Greta Gerwig',
        posterUrl: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=pBk4NYhWNMM',
        date: new Date('2025-12-31'),
        time: '11:00',
        venue: 'Cinepolis',
        screen: 'Screen 3',
        totalSeats: 100,
        availableSeats: 75,
        price: 320,
        format: '2D',
        status: 'now-showing',
      },
    ];
    
    await Show.insertMany(shows);
    console.log(`✅ Successfully seeded ${shows.length} shows to the database!`);
    process.exit();
  })
  .catch(err => {
    console.error('❌ Error seeding database:', err);
    process.exit(1);
  });
